### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hroland** [Moukrea/retrowave-scene#2]
Hey @Moukrea!

Crazy impressive project 🤯 We love it so much here at Extra, we'd love to utilize it in one of our upcoming projects.

Does the repo have any licensing guidelines? Is commercial use allowed?

thanks! :)

**Comment by Moukrea** [comment]
> Hey @Moukrea!
> 
> Crazy impressive project 🤯 We love it so much here at Extra, we'd love to utilize it in one of our upcoming projects.
> 
> Does the repo have any licensing guidelines? Is commercial use allowed?
> 
> thanks! :)

Thanks for the kind words 😃 Here it goes, this repo is under MIT license 😉
